[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Custom partisi OTA — support kamera + OTA update
; WAJIB flash ulang via USB pertama kali ganti partisi!
board_build.partitions = partitions_ota.csv
board_build.filesystem = spiffs

upload_speed = 921600

lib_deps =
  adafruit/Adafruit Fingerprint Sensor Library@^2.1.0
  bblanchon/ArduinoJson@^7.0.0

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
